// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class InventoryForm : UGuiForm
    {
        [SerializeField] private InventoryView _view = null;

        public InventoryView View => _view;
    }
}
