// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class InventoryView : MonoBehaviour
    {
        [SerializeField] public global::TMPro.TMP_InputField searchInput;
        [SerializeField] public global::UnityEngine.UI.Button sortButton;
        [SerializeField] public global::UnityEngine.UI.ScrollRect itemScroll;
        [SerializeField] public global::UnityEngine.RectTransform warehouseSlotRoot;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem warehouseSlotTemplate;
    }
}
