// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CombatReadinessView : MonoBehaviour
    {
        [SerializeField] public global::TMPro.TextMeshProUGUI storageText;
        [SerializeField] public global::SepCore.UI.SquadForm squadForm;
        [SerializeField] public global::SepCore.UI.DeploymentForm deploymentForm;
    }
}
