// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class CombatReadinessForm : UGuiForm
    {
        [SerializeField] private CombatReadinessView _view = null;

        public CombatReadinessView View => _view;
    }
}
