// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class WarehouseView : MonoBehaviour
    {
        [SerializeField] public global::SepCore.UI.InventoryForm inventoryPanelForm;
        [SerializeField] public global::SepCore.UI.ItemDetailsForm itemDetailsPanelForm;
    }
}
