// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class WarehouseView : MonoBehaviour
    {
        [SerializeField] public global::SepCore.UI.InventoryView inventoryPanelView;
        [SerializeField] public global::SepCore.UI.ItemDetailsView itemDetailsPanelView;
    }
}
