// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class WarehouseForm : UGuiForm
    {
        [SerializeField] private WarehouseView _view = null;

        public WarehouseView View => _view;
    }
}
