// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDetailsForm : UGuiForm
    {
        [SerializeField] private ItemDetailsView _view = null;

        public ItemDetailsView View => _view;
    }
}
