// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDetailsView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Image itemDetailIcon;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailNameText;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailTypeText;
        [SerializeField] public global::TMPro.TextMeshProUGUI hpText;
        [SerializeField] public global::TMPro.TextMeshProUGUI atkText;
        [SerializeField] public global::TMPro.TextMeshProUGUI mpText;
        [SerializeField] public global::TMPro.TextMeshProUGUI matText;
        [SerializeField] public global::TMPro.TextMeshProUGUI speedText;
        [SerializeField] public global::TMPro.TextMeshProUGUI stackText;
        [SerializeField] public global::TMPro.TextMeshProUGUI itemDetailDescriptionText;
        [SerializeField] public global::UnityEngine.UI.Button openLoadoutButton;
    }
}
