// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class LobbyView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Toggle homeToggle;
        [SerializeField] public global::UnityEngine.RectTransform selectionMarkerObject;
        [SerializeField] public global::UnityEngine.UI.Toggle warehouseToggle;
        [SerializeField] public global::UnityEngine.UI.Toggle loadoutToggle;
        [SerializeField] public global::SepCore.UI.CombatReadinessForm combatRandinessForm;
        [SerializeField] public global::SepCore.UI.WarehouseForm warehouseForm;
    }
}
