// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class LobbyView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Button homeButton;
        [SerializeField] public global::UnityEngine.RectTransform selectionMarkerObject;
        [SerializeField] public global::UnityEngine.UI.Button warehouseButton;
        [SerializeField] public global::UnityEngine.UI.Button loadoutButton;
        [SerializeField] public global::SepCore.UI.WarehouseView warehouseView;
        [SerializeField] public global::SepCore.UI.CombatReadinessView combatRandinessView;
    }
}
