// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class LobbyForm : UGuiForm
    {
        [SerializeField] private LobbyView _view = null;

        public LobbyView View => _view;
    }
}
