// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDetailsPanelView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Image itemDetailIcon;
        [SerializeField] public global::UnityEngine.UI.Text nameText;
        [SerializeField] public global::UnityEngine.UI.Text typeText;
        [SerializeField] public global::UnityEngine.UI.Text hpText;
        [SerializeField] public global::UnityEngine.UI.Text atkText;
        [SerializeField] public global::UnityEngine.UI.Text mpText;
        [SerializeField] public global::UnityEngine.UI.Text matText;
        [SerializeField] public global::UnityEngine.UI.Text speedText;
        [SerializeField] public global::UnityEngine.UI.Text stackText;
        [SerializeField] public global::UnityEngine.UI.Button openLoadoutButton;
    }
}
