// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class ItemDetailsPanelForm : UGuiForm
    {
        [SerializeField] private ItemDetailsPanelView _view = null;

        public ItemDetailsPanelView View => _view;
    }
}