// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class MainWarehouseForm : UGuiForm
    {
        [SerializeField] private MainWarehouseView _view = null;

        public MainWarehouseView View => _view;
    }
}
