// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class MainWarehouseView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Button homeButton;
        [SerializeField] public global::UnityEngine.UI.Button warehouseButton;
        [SerializeField] public global::UnityEngine.UI.Button loadoutButton;
        [SerializeField] public global::UnityEngine.UI.InputField searchInput;
        [SerializeField] public global::UnityEngine.UI.Button sortButton;
        [SerializeField] public global::UnityEngine.UI.ScrollRect itemScroll;
        [SerializeField] public global::UnityEngine.RectTransform warehouseSlotRoot;
        [SerializeField] public global::SepCore.UI.WarehouseSlotItem warehouseSlotTemplate;
        [SerializeField] public global::UnityEngine.UI.Text itemCountText;
        [SerializeField] public global::SepCore.UI.ItemDetailsView itemDetailsView;
    }
}
