// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class DeploymentView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.UI.Toggle tier1Toggle;
        [SerializeField] public global::UnityEngine.UI.Toggle tier2Toggle;
        [SerializeField] public global::UnityEngine.UI.Toggle tier3Toggle;
        [SerializeField] public global::TMPro.TMP_InputField seedInput;
        [SerializeField] public global::UnityEngine.UI.Button randomizeButton;
        [SerializeField] public global::TMPro.TextMeshProUGUI partySizeText;
        [SerializeField] public global::TMPro.TextMeshProUGUI mapIdText;
        [SerializeField] public global::TMPro.TextMeshProUGUI timeLimitText;
        [SerializeField] public global::UnityEngine.UI.Button beginRunButton;
    }
}
