// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class DeploymentForm : UGuiForm
    {
        [SerializeField] private DeploymentView _view = null;

        public DeploymentView View => _view;
    }
}
