// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class BattleForm : UGuiForm
    {
        [SerializeField] private BattleView _view = null;

        public BattleView View => _view;
    }
}
