// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class BattleView : MonoBehaviour
    {
        [SerializeField] public global::UnityEngine.RectTransform turnSlotsRoot;
        [SerializeField] public global::SepCore.UI.BattleTurnSlotItem battleTurnSlotTemplate;
        [SerializeField] public global::SepCore.UI.BattleActorCardItem playerCard1;
        [SerializeField] public global::SepCore.UI.BattleActorCardItem playerCard2;
        [SerializeField] public global::SepCore.UI.BattleActorCardItem playerCard3;
        [SerializeField] public global::SepCore.UI.BattleActorCardItem playerCard4;
        [SerializeField] public global::UnityEngine.RectTransform enemySlotsRoot;
        [SerializeField] public global::SepCore.UI.BattleEnemySlotItem battleEnemySlotTemplate;
        [SerializeField] public global::TMPro.TextMeshProUGUI currentActorText;
        [SerializeField] public global::UnityEngine.UI.Button attackButton;
        [SerializeField] public global::UnityEngine.UI.Button skillButton;
        [SerializeField] public global::UnityEngine.UI.Button itemButton;
        [SerializeField] public global::UnityEngine.UI.Button escapeButton;
    }
}
