// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class JoystickForm : UGuiForm
    {
        [SerializeField] private JoystickView _view = null;

        public JoystickView View => _view;
    }
}
