// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class JoystickView : MonoBehaviour
    {
        [SerializeField] public global::VariableJoystick joystick;
        [SerializeField] public global::SepCore.UI.UIInteractButtonListener interactListener;
    }
}
