// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class SquadForm : UGuiForm
    {
        [SerializeField] private SquadView _view = null;

        public SquadView View => _view;
    }
}
