// <auto-generated />
using UnityEngine;

namespace SepCore.UI
{
    [DisallowMultipleComponent]
    public partial class InventoryPanelForm : UGuiForm
    {
        [SerializeField] private InventoryPanelView _view = null;

        public InventoryPanelView View => _view;
    }
}
